Make compatible with pymbar 3 and 4
choderalab/openmmtools pull request #630
Opened 2022-11-21 20:41 UTC by mattwthompson

## Description
Provide a brief description of the PR's purpose here.

## Todos
- [ ] Implement feature / fix bug
- [ ] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
- [ ] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
- [ ] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst) to summarize changes in behavior, enhancements, and bugfixes implemented in this PR

## Status
- [ ] Ready to go

## Changelog message
```

```

2023-02-03 18:36 UTC, mikemhenry commented
@mattwthompson Looking at this now, what is left to do?

2023-02-03 18:40 UTC, mikemhenry commented
@mattwthompson I will give you write access to this repo, then you can push this branch directly so openeye will work. Or I can just take over the PR and push it myself, let me know what you rather do

2023-02-03 19:37 UTC, ijpulidos commented
We shouldn't be needing openeye for openmmtools

2023-02-03 19:41 UTC, ijpulidos requested changes
Minor code change to fix the tests. Pymbar 3 `getFreeEnergyDifferences` should actually return 2 objects by default.

2023-02-03 19:41 UTC, ijpulidos commented on openmmtools/multistate/multistateanalyzer.py
>              (Deltaf_ij, dDeltaf_ij, _) = self.mbar.getFreeEnergyDifferences()
This should fix the failing tests.
```suggestion
            Deltaf_ij, dDeltaf_ij = self.mbar.getFreeEnergyDifferences()
```
pymbar 3 actually returns two things by default, unless we specify `return_theta=True`.

2023-02-14 17:41 UTC, mattwthompson commented
Sorry, I let the invitation expire by not getting to it in time. These changes shouldn't touch OpenEye but I can re-open this to an upstream branch if it ends up being needed.

It looks like it's only needed for generating data for tests, not actual API calls:

```console
$ grep -r openeye .
./openmmtools/testsystems.py:    molecule : openeye.oechem.OEMol
./openmmtools/testsystems.py:    from openeye import oechem
Binary file ./openmmtools/__pycache__/testsystems.cpython-39.pyc matches
./openmmtools/data/benzene-toluene-implicit/generate-molecules.py:from openeye import oechem
./openmmtools/data/benzene-toluene-implicit/generate-molecules.py:from openeye import oeomega
./openmmtools/data/benzene-toluene-implicit/generate-molecules.py:from openeye import oeiupac
./openmmtools/data/benzene-toluene-implicit/generate-molecules.py:from openeye import oequacpac
./openmmtools/data/cb7-viologen/molecules/create-viologen.py:from openeye.oechem import *
./openmmtools/data/cb7-viologen/molecules/create-viologen.py:from openeye.oeomega import *
./openmmtools/data/cb7-viologen/molecules/create-viologen.py:from openeye.oequacpac import *

2023-02-14 19:27 UTC, ijpulidos commented
Thanks a lot @mattwthompson , this is looking good! Please let us know if this is good to be merged

2023-02-14 20:19 UTC, mattwthompson commented
I think this is good to go - in the sense that I implemented what I set out to do originally. The log of these tests is pretty much meaningless to me so I'm not sure if these tests are actually passing or not?

2023-02-14 20:37 UTC, ijpulidos commented
@mattwthompson I think the fails in the tests are unrelated with the changes in this PR. More info at #654 . Once we review and merge that one, tests here should run fine. Thanks!

2023-02-21 18:30 UTC, ijpulidos commented
We are hitting random fails in the tests as in https://github.com/choderalab/openmmtools/actions/runs/4227354498/jobs/7341747889#step:9:3130

I can reproduce this behavior locally, sometimes it passes sometimes it fails when using `pymbar=4.0.1`.  Whereas it seems to pass every time I run them with `pymbar=3.1.1`

2023-02-21 18:37 UTC, ijpulidos commented
Oh even though we are testing with both versions and they both seem to be failing here in github actions. Locally they only fail with pymbar=4.0.1 for me.

2023-03-20 14:25 UTC, ijpulidos commented
This was superseded byt #659 . Closing. Thanks @mattwthompson for all the work!

2023-03-20 14:25 UTC, closed without merging