manually casting objects to np arrays when reading checkpoint
choderalab/openmmtools pull request #701
Opened 2023-05-31 19:56 UTC by ijpulidos

## Description
Numba 0.57 explicitly raises an exception when trying to use `MaskedArrays` in `@jit` decorated functions. When we are reading `MultiStateSampler` attributes from serialized objects (storage) these attributes become `MaskedArray`. We are casting them to arrays here to make sure we can still use numba when mixing replicas.

Solves #700 

## Todos
- [x] Implement feature / fix bug
- [ ] Add [tests](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests)
- [ ] Update [documentation](https://github.com/choderalab/openmmtools/tree/master/docs) as needed
- [ ] Update [changelog](https://github.com/choderalab/openmmtools/blob/master/docs/releasehistory.rst) to summarize changes in behavior, enhancements, and bugfixes implemented in this PR

## Status
- [ ] Ready to go

## Changelog message
```
Support for latest numba 0.57 by deserializing attributes as numpy arrays instead of MaskedArrays.
```

2023-05-31 20:00 UTC, mikemhenry commented
Any ideas on the consequence of this?

2023-05-31 20:01 UTC, mikemhenry commented
We might need to check the mask to make sure this is safe
https://numpy.org/doc/stable/reference/maskedarray.generic.html#what-is-a-masked-array

2023-05-31 22:17 UTC, mikemhenry commented
Ah so we are not using the actual masking functionality here? I'm just worried that if there is a mask on these arrays, that means we don't want to include some of that data in the analysis.

2023-06-01 16:06 UTC, mikemhenry requested changes
Just want to make sure that we are not using the mask

2023-06-01 18:02 UTC, ijpulidos commented
> Just want to make sure that we are not using the mask
I think we don't use it or needing, since they weren't masked array from the start and resuming simulations seems to be working. That said, I cannot be completely sure.

I don't know of a systematic way to be sure we are not using the mask, it just seems that every time we read from a .nc file we will always get a `MaskedArray` , as in https://github.com/Unidata/netcdf4-python/pull/787

2023-06-01 18:05 UTC, ijpulidos commented
We could probably come up with a less hacky or a more general solution that uses `set_auto_mask(False)` whenever we read from the .nc files

2023-06-01 21:44 UTC, mikemhenry commented
If we don't want the masking behavior or use it, then when we save the nc file we should use `set_auto_mask(False)` but it sounds like this is okay to merge then

2023-06-01 21:44 UTC, mikemhenry approved these changes

2023-06-01 22:17 UTC, merged